name: gsheet.action test
on: push
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v2.1.0
        with:
          spreadsheetId: ${{ secrets.SHEET_ID }}
          commands: |
            [
              { "command": "getData", "args": { "range": "'<worksheetTitle>'!A2:B3" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.API_KEY }}
      - name: dump results
        env:
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
      - name: Log results
        run: echo "${{ steps.update_worksheet.outputs.results }}" >> results.log
