name: Fetch Google Sheet Data
on:
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: googlesheet_actions
        uses: rjoydip/googlesheet-actions@0.1.1
        with:
          sheet-id: ${{ secrets.SHEET_ID }}
          api-key: ${{ secrets.API_KEY }}
          client-email: ${{ secrets.CLIENT_EMAIL }}
      - name: Save data to JSON file
        run: |
          echo '${{ steps.googlesheet_actions.outputs.result }}' > data.json
      - name: Commit and push if it changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data"
          git push
